[tool.poetry]
name = "politylink"
version = "0.1.1"
description = ""
authors = ["Mitsuki Usui"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
